firstCoreapp/Controllers/categoryController.cs
using firstCoreapp.Models;
using firstCoreapp.Repository.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace firstCoreapp.Controllers
{
    [Authorize(Roles = clsRoles.roleAdmin)]
    public class categoryController : Controller
    {
        public categoryController(//IRepository<category> repository
                                  IUnitOfWork _myUnit)
        {
            //_repository = repository;
            myUnit = _myUnit;
           
        }
        
        //private IRepository<category> _repository;
        private readonly IUnitOfWork myUnit;
     

        public async Task<IActionResult> Index()
        {
            return View(await myUnit.categories.FindAllAsync("items"));
        }

        
        public IActionResult delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var i = myUnit.categories.Find(id);
            if (i == null)
            {
                return BadRequest();
            }
            
            myUnit.categories.DeleteOne(i);
         
            
            TempData["success"] = "transaction was success";
            return RedirectToAction("Index");

        }

        public IActionResult insertorEdit(int? id)
        { 

            
           
            if (id == 0 || id == null)
            {
                category c = new category();
                return View(c);
            }

            var i = myUnit.categories.selectone( X => X.Id == id);
            if (i == null)
            {
                return BadRequest();
            }
            else
            {
               
                return View(i);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult insertorEdit(category t)
        {
            if (t.Name.Contains("0") || t.Name.Contains("1") || t.Name.Contains("2") || t.Name.Contains("3") || t.Name.Contains("4") || t.Name.Contains("5") || t.Name.Contains("6") || t.Name.Contains("7") || t.Name.Contains("8") || t.Name.Contains("9"))
            {
                ModelState.AddModelError("Name", "Name can't contains number");
            }

            if (ModelState.IsValid)
            {
              
                if (t.clientFile != null)
                {
                    MemoryStream stream= new MemoryStream();
                    
                    t.clientFile.CopyTo(stream);
                    t.dbimage = stream.ToArray();
                }

                    if (t.Id == 0)
                {
                    myUnit.categories.Addone(t);
                }
                else
                {
                    myUnit.categories.UpdateOne(t);
                }

              

                TempData["success"] = "transaction was success";
                return RedirectToAction("Index");

            }
            else
            {
                return View(t);
            }
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
           /* myUnit.Dispose();*/       
        }
    }
}

firstCoreapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Zamazon</title>
    <link rel="stylesheet" href="~/css/skitchy.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/firstCoreapp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Zamazon</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>s
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
            
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="items" asp-action="Index">items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="category" asp-action="Index">category List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Employees" asp-controller="home" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Employees" asp-controller="Employees" asp-action="Index">Employees List</a>
                      
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">User Roles</a>
                        </li>
                     
                     
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
                </div>
               
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" position= "absolute" bottom = "0px">
        <div class="container">
            &copy; 2023 - Zamazon - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> 
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

firstCoreapp/Views/Shared/_notify.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

@if (TempData["success"] != null)
{
    <script type="text/javascript">
        toastr.success('@TempData["success"].ToString()', 'success');
    </script>
}